

/*
 * @AUTHOR Felix
 */

package FrontEnd;

import BackEnd.Configuration.ConfigurationIZV;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;


public class MainMenu extends JFrame implements Themeable {

    private JPanel panelLogin;
    private JButton loginbutton;
    private JButton configLoginButton;
    private JLabel login_label;


    public MainMenu() {

        login_label.setText("Bienvenido, " + System.getProperty("user.name"));
        configLoginButton.setName("configLoginButton");
        loginbutton.setName("loginbutton");


        setIcons();
        initComponents();


    }


    public void initComponents() {

        // set configLoginButton the same name as it is declared as, without using a literal string, so it is automated


        setSize(800, 600);
        setTitle("IZV Lab Management Tool 2024");
        setContentPane(panelLogin);
        setVisible(true);
        setResizable(false);
        pack();

    }


    @Override
    public void setIcons() {

        // Se puede hacer global y constante esta funcion, ire viendo la implementacion más adelante.


        for (Component component : panelLogin.getComponents()) {

            if (component instanceof JButton) {

                JButton button = (JButton) component;

                if (button.getName() == null) {
                    continue;
                }

                if (ConfigurationIZV.getInstance().getAppearance().equals("OSCURO")) {


                    button.setIcon(new ImageIcon("src/main/resources/icons/white/" + button.getName() + ".png"));

                } else {

                    button.setIcon(new ImageIcon("src/main/resources/icons/black/" + button.getName() + ".png"));


                }


            }


        }


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelLogin = new JPanel();
        panelLogin.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow"));
        loginbutton = new JButton();
        loginbutton.setHorizontalAlignment(0);
        loginbutton.setHorizontalTextPosition(11);
        loginbutton.setText("Login");
        CellConstraints cc = new CellConstraints();
        panelLogin.add(loginbutton, cc.xy(1, 3));
        login_label = new JLabel();
        login_label.setText("Bienvenido,");
        panelLogin.add(login_label, cc.xy(1, 1));
        configLoginButton = new JButton();
        configLoginButton.setHorizontalTextPosition(10);
        configLoginButton.setText("");
        panelLogin.add(configLoginButton, cc.xy(3, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelLogin;
    }

}
